#pragma once

// Umbrella for all external-header gateways. Domain code should include specific
// base/gateway/C*.hpp headers (or util/StdLib.hpp), not <cmath>/<vector>/etc. directly.

#include "Calgorithm.hpp"
#include "Carray.hpp"
#include "Cassert.hpp"
#include "Catomic.hpp"
#include "Ccctype.hpp"
#include "Cchrono.hpp"
#include "CconditionVariable.hpp"
#include "Ccstdlib.hpp"
#include "Ccstring.hpp"
#include "Cctime.hpp"
#include "Cdeque.hpp"
#include "Cfstream.hpp"
#include "Cfunctional.hpp"
#include "Ciomanip.hpp"
#include "Ciostream.hpp"
#include "Cios.hpp"
#include "Climits.hpp"
#include "Cmap.hpp"
#include "Cmath.hpp"
#include "Cmemory.hpp"
#include "Cmutex.hpp"
#include "Coptional.hpp"
#include "Cposix.hpp"
#include "Cqueue.hpp"
#include "Cset.hpp"
#include "Csstream.hpp"
#include "Cstddef.hpp"
#include "Cstdint.hpp"
#include "Cstring.hpp"
#include "Cthread.hpp"
#include "Ctypeindex.hpp"
#include "Cunordered_map.hpp"
#include "Cunordered_set.hpp"
#include "Cutility.hpp"
#include "Cvariant.hpp"
#include "Cvector.hpp"
#include "Cwin.hpp"
